"""Compile a SKILL.md from a BuildContext.

This is intentionally a template-based first pass. The output is
a well-structured SKILL.md that captures everything LSD knows from
the source. Future: drive this with an LLM call for richer output.
"""

from __future__ import annotations

from lsd.models import BuildContext


def compile_skill(ctx: BuildContext) -> str:
    """Return the SKILL.md content as a string."""
    fetch = ctx.ingestion.fetch
    fit = ctx.source_fit
    opp = ctx.opportunity_map
    mode = ctx.ingestion.mode

    skill_type = opp.recommended_skill_type.replace("_", " ").title()
    name = f"{skill_type} — from {fetch.title[:60]}"

    caveat_block = _caveat_block(mode)

    return f"""---
name: {name}
version: 0.1.0
summary: Auto-generated by LSD from {fetch.canonical_url}
description: >-
  Use this skill when working with content derived from: {fetch.title}.
  Skill type: {skill_type}. Ingestion mode: {mode}.
allowed-tools: Read, Write, Edit
---

## Purpose

This skill was compiled by LSD from the following source:
- URL: {fetch.canonical_url}
- Title: {fetch.title}
- Ingestion mode: {mode}
- Skill type: {skill_type}

Review and refine this file before use. The sections below are
seeded from source signals and should be expanded with domain knowledge.

## When to use

Use this skill when asked to perform tasks related to:
{_usage_hints(fit, opp.recommended_skill_type)}

## Core principle

<!-- TODO: distil the source's central idea into one sentence. -->

## Workflow

<!-- TODO: expand from the source's procedure signals. -->
1. Read the input in full.
2. Apply the relevant checks or procedures from the source.
3. Produce structured output.

## Output format

<!-- TODO: define the expected output structure. -->
Provide structured output with:
- Finding or step name
- Evidence or rationale
- Recommended action

## Style rule

Be specific and actionable. Prefer direct language over hedged summaries.

## Caveats

{caveat_block}

## Source

- Compiled from: {fetch.canonical_url}
- Source fit: {fit.overall_fit} (rule: {fit.rule_density}, procedure: {fit.procedure_density}, example: {fit.example_density})
- Notes: {fit.fit_notes}
"""


def _usage_hints(fit, skill_type: str) -> str:
    hints = []
    if fit.rule_density == "high":
        hints.append("- Reviewing or auditing content against a set of rules or heuristics")
    if fit.procedure_density == "high":
        hints.append("- Following or planning a multi-step workflow")
    if fit.example_density == "high":
        hints.append("- Applying worked examples to a new problem")
    hints.append(f"- Tasks of type: {skill_type.replace('_', ' ')}")
    return "\n".join(hints) if hints else "- General tasks related to the source domain"


def _caveat_block(mode: str) -> str:
    base = "This skill was auto-generated by LSD and should be reviewed before use."
    if mode == "hybrid":
        return (
            f"{base} The source was ingested in hybrid mode; "
            "visual artifacts are preserved alongside text. "
            "Check the visual/ directory if layout-dependent meaning matters."
        )
    if mode == "visual-first":
        return (
            f"{base} The source was ingested in visual-first mode; "
            "the primary artifact is a rendered screenshot. "
            "Text extraction may be incomplete."
        )
    return base
