"""Write a complete LSD skill package to disk."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from lsd import __version__ as lsd_version
from lsd.compiler import compile_skill, compile_skill_multi
from lsd.models import BuildContext, MultiSourceBuildContext
from lsd.normaliser import content_hash, normalise


def write_package(ctx: BuildContext) -> Path:
    """Write all package files to ctx.output_dir. Returns the output directory."""
    out = ctx.output_dir
    out.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).isoformat()
    ctx.generated_at = generated_at

    fetch = ctx.ingestion.fetch
    mode = ctx.ingestion.mode
    opp = ctx.opportunity_map

    normalised = normalise(fetch)
    norm_hash = content_hash(normalised)

    # Compile SKILL.md and capture the model that did it
    skill_content, compiler_model = compile_skill(ctx)
    (out / "SKILL.md").write_text(skill_content)

    # source.md
    (out / "source.md").write_text(normalised)

    # metadata.json — includes compiler_model
    (out / "metadata.json").write_text(
        json.dumps(_build_metadata(ctx, norm_hash, generated_at, compiler_model), indent=2)
    )

    # source-policy.md
    (out / "source-policy.md").write_text(_source_policy(fetch.canonical_url, mode))

    # skill-opportunities.md
    (out / "skill-opportunities.md").write_text(_opportunities_md(opp))

    # extraction-report.md
    (out / "extraction-report.md").write_text(_extraction_report(ctx))

    # CHANGELOG.md
    (out / "CHANGELOG.md").write_text(
        f"# Changelog\n\n## 0.1.0 — {generated_at[:10]}\n- Initial package generated by LSD.\n"
    )

    # README.md — first-class package output (agent entry point for versioning)
    (out / "README.md").write_text(
        _readme(ctx, norm_hash, generated_at, compiler_model)
    )

    # visual/ placeholder for hybrid/visual-first
    if mode in ("hybrid", "visual-first"):
        visual_dir = out / "visual" / "tiles"
        visual_dir.mkdir(parents=True, exist_ok=True)
        (out / "visual" / ".gitkeep").touch()

    return out


def write_multi_package(ctx: MultiSourceBuildContext) -> Path:
    """Write multi-source build artifacts to ctx.output_dir.

    Compiles SKILL.md (with compiler_model) inside this function so the
    model id is available for metadata.json and README.md. Retrieval
    backend is taken from ctx._retrieval_backend / ctx._retrieval_index
    if available (set by pipeline.build_multi).
    """
    out = ctx.output_dir
    out.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).isoformat()

    # Per-source files
    for entry in ctx.sources:
        path = out / f"source-{entry.index}.md"
        path.write_text(entry.normalised, encoding="utf-8")

    # sources-index.md
    lines: list[str] = [
        "# Sources Index\n\n",
        f"Built: {generated_at}\n\n",
        f"Sources: {len(ctx.sources)}\n\n",
        "| # | URL | Type | Mode | Overall Fit |\n",
        "|---|-----|------|------|-------------|\n",
    ]
    for e in ctx.sources:
        source_type = e.source_type if isinstance(e.source_type, str) else str(e.source_type)
        ingestion_mode = e.ingestion_mode if isinstance(e.ingestion_mode, str) else str(e.ingestion_mode)
        overall_fit = getattr(e.fit, "overall_fit", "—")
        lines.append(
            f"| {e.index} | {e.url} | {source_type} | {ingestion_mode} | {overall_fit} |\n"
        )
    (out / "sources-index.md").write_text("".join(lines), encoding="utf-8")

    # conflicts.md
    conflict_lines: list[str] = [
        "# Conflict Report\n\n",
        f"{ctx.conflict_report.summary}\n\n",
    ]
    if ctx.conflict_report.has_blocking_conflicts:
        conflict_lines.append(
            "> **Warning:** High-severity contradictions detected. "
            "Review before using this skill.\n\n"
        )
    if not ctx.conflict_report.conflicts:
        conflict_lines.append("No conflicts detected.\n")
    else:
        for i, c in enumerate(ctx.conflict_report.conflicts, 1):
            conflict_lines.extend([
                f"## Conflict {i}: {c.kind.title()} [{c.severity.upper()}]\n\n",
                f"**Sources involved:** {', '.join(str(s) for s in c.source_indices)}\n\n",
                f"**Description:** {c.description}\n\n",
                f"**Suggestion:** {c.suggestion}\n\n",
            ])
    (out / "conflicts.md").write_text("".join(conflict_lines), encoding="utf-8")

    # skill-opportunities.md
    opp = ctx.combined_opportunities
    (out / "skill-opportunities.md").write_text(_opportunities_md(opp), encoding="utf-8")

    # Compile SKILL.md — retrieval backend may be pre-attached by build_multi()
    ret_backend = getattr(ctx, "_retrieval_backend", None)
    ret_index = getattr(ctx, "_retrieval_index", None)
    skill_content, compiler_model = compile_skill_multi(
        ctx,
        retrieval_backend=ret_backend if ret_index is not None else None,
    )
    (out / "SKILL.md").write_text(skill_content, encoding="utf-8")

    # metadata.json — v0.5 schema, compiler_model now populated
    meta = _build_metadata_multi(ctx, generated_at, compiler_model)
    (out / "metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    # README.md — agent entry point for versioning (multi-source variant)
    (out / "README.md").write_text(
        _readme_multi(ctx, generated_at, compiler_model), encoding="utf-8"
    )

    # index.md
    index_lines: list[str] = [
        "# LSD Multi-Source Build\n\n",
        f"Sources: {len(ctx.sources)}\n\n",
        "## Files\n\n",
    ]
    for e in ctx.sources:
        index_lines.append(f"- [source-{e.index}.md](source-{e.index}.md) — {e.url}\n")
    index_lines.extend([
        "- [sources-index.md](sources-index.md)\n",
        "- [conflicts.md](conflicts.md)\n",
        "- [skill-opportunities.md](skill-opportunities.md)\n",
        "- [metadata.json](metadata.json)\n",
        "- [README.md](README.md)\n",
        "- [SKILL.md](SKILL.md)\n",
    ])
    (out / "index.md").write_text("".join(index_lines), encoding="utf-8")

    return out


# ---------------------------------------------------------------------------
# README generators
# ---------------------------------------------------------------------------

def _readme(ctx: BuildContext, norm_hash: str, generated_at: str, compiler_model: str | None) -> str:
    """Generate README.md — the agent's entry point for this skill package."""
    fetch = ctx.ingestion.fetch
    fit = ctx.source_fit
    opp = ctx.opportunity_map
    mode = ctx.ingestion.mode

    skill_type = opp.recommended_skill_type.replace("_", " ").title()
    compiler_note = (
        f"Compiled by `{compiler_model}`."
        if compiler_model
        else "Compiled with heuristic fallback (no LLM configured)."
    )

    candidate_rows = "\n".join(
        f"| {c.type} | {c.confidence} | {c.build_timing} | {c.why_fit} |"
        for c in opp.candidates
    )

    return f"""# {skill_type} — LSD Skill Package

> Auto-generated by [LSD](https://github.com/moondocksaint/lsd) v{lsd_version}.
> Review and refine before promoting to production use.

## When to use

Use this skill for **{skill_type.lower()}** tasks drawing on:
- Source: [{fetch.title}]({fetch.canonical_url})

## Package structure

```
<package-dir>/
├── README.md               ← you are here; start here for versioning
├── SKILL.md                ← load this into your agent
├── source.md               ← normalised source text
├── source-policy.md        ← update policy, fallback chain
├── skill-opportunities.md  ← other skill types this source supports
├── extraction-report.md    ← classification scores and routing rationale
├── metadata.json           ← machine-readable provenance (hash, model, timestamps)
└── CHANGELOG.md            ← human-readable version history
```

## Version & update workflow

Run `lsd check <package-dir>` to detect source drift. Change states:
- **Unchanged** — hash identical, no action needed
- **Minor** — content changed, structure intact; offer rebuild
- **Substantial** — major rewrite; warn user, do not auto-overwrite
- **Gone** — 404/unreachable; preserve existing package, use fallback chain
- **Redirected** — URL moved; offer to update canonical URL

Machine-readable provenance in `metadata.json`:
- `source_dependency.normalized_hash` — fingerprint of the normalised source
- `source_dependency.last_checked_at` — timestamp of last fetch
- `package.compiler_model` — which LLM compiled the skill sections
- `package.lsd_version` — LSD version that built this package

## Source provenance

| Field | Value |
|-------|-------|
| URL | [{fetch.canonical_url}]({fetch.canonical_url}) |
| Title | {fetch.title} |
| Ingestion mode | `{mode}` |
| Overall fit | `{fit.overall_fit}` |
| Rule density | `{fit.rule_density}` |
| Example density | `{fit.example_density}` |
| Content hash | `{norm_hash}` |
| Built at | `{generated_at}` |
| Compiler | `{compiler_model or "heuristic (no LLM)"}` |
| LSD version | `{lsd_version}` |

## Skill opportunities

| Type | Confidence | Timing | Rationale |
|------|-----------|--------|-----------|
{candidate_rows}

## Governance

- Promotion policy: **manual approval required**
- Auto-update threshold: **never**
- Change classification: unchanged / minor / substantial / gone / redirected
- Review `source-policy.md` before promoting any update.

---

*{compiler_note} Generated by LSD v{lsd_version}.*
"""


def _readme_multi(
    ctx: MultiSourceBuildContext,
    generated_at: str,
    compiler_model: str | None,
) -> str:
    """Generate README.md for a multi-source skill package."""
    opp = ctx.combined_opportunities
    skill_type = opp.recommended_skill_type.replace("_", " ").title()
    compiler_note = (
        f"Compiled by `{compiler_model}`."
        if compiler_model
        else "Compiled with heuristic fallback (no LLM configured)."
    )

    source_rows = "\n".join(
        f"| {e.index} | [{e.url}]({e.url}) | "
        f"`{content_hash(e.normalised)}` | "
        f"`{getattr(e.fit, 'overall_fit', '—')}` |"
        for e in ctx.sources
    )

    conflict_note = ""
    if ctx.conflict_report.has_blocking_conflicts:
        conflict_note = (
            "\n> **Warning:** Blocking conflicts detected across sources. "
            "See `conflicts.md` before using this skill.\n"
        )
    elif ctx.conflict_report.conflicts:
        conflict_note = f"\n> Note: {ctx.conflict_report.summary} See `conflicts.md`.\n"

    return f"""# {skill_type} (Multi-Source) — LSD Skill Package

> Auto-generated by [LSD](https://github.com/moondocksaint/lsd) v{lsd_version}
> from {len(ctx.sources)} sources.
> Review and refine before promoting to production use.
{conflict_note}
## When to use

Use this skill for **{skill_type.lower()}** tasks that draw on multiple sources.
Each claim in `SKILL.md` is cited with [Source N] for traceability.

## Package structure

```
<package-dir>/
├── README.md               ← you are here; start here for versioning
├── SKILL.md                ← load this into your agent (multi-source compiled)
├── index.md                ← package overview and file map
├── sources-index.md        ← fetch status and fit scores per source
├── source-1.md … source-N.md  ← normalised per-source text
├── conflicts.md            ← cross-source gaps, contradictions, overlaps
├── skill-opportunities.md  ← skill types detected across all sources
└── metadata.json           ← machine-readable provenance
```

## Version & update workflow

Run `lsd check <package-dir>` to detect drift in any source. Drift in
any one source triggers a check report for all sources. Change states:
- **Unchanged** — all hashes identical, no action needed
- **Minor** — one or more sources changed, structure intact
- **Substantial** — major rewrite in any source; warn, do not auto-overwrite
- **Gone** — a source URL is 404/unreachable; preserve package, use fallback
- **Redirected** — a source URL moved; offer to update canonical URL

## Source provenance

| # | URL | Content Hash | Overall Fit |
|---|-----|-------------|-------------|
{source_rows}

| Field | Value |
|-------|-------|
| Built at | `{generated_at}` |
| Compiler | `{compiler_model or "heuristic (no LLM)"}` |
| LSD version | `{lsd_version}` |
| Conflicts | {ctx.conflict_report.summary} |

## Governance

- Promotion policy: **manual approval required**
- Auto-update threshold: **never**
- Resolve all blocking conflicts in `conflicts.md` before promoting.

---

*{compiler_note} Generated by LSD v{lsd_version}.*
"""


# ---------------------------------------------------------------------------
# Metadata builders
# ---------------------------------------------------------------------------

def _build_metadata(
    ctx: BuildContext,
    norm_hash: str,
    generated_at: str,
    compiler_model: str | None = None,
) -> dict:
    fetch = ctx.ingestion.fetch
    mode = ctx.ingestion.mode
    fit = ctx.source_fit
    opp = ctx.opportunity_map

    visual_artifacts: list[str] = []
    if mode in ("hybrid", "visual-first"):
        visual_artifacts = ["visual/rendered-page.png", "visual/tiles/"]

    return {
        "package": {
            "name": opp.recommended_skill_type.replace("_", " ").title(),
            "version": "0.1.0",
            "generated_at": generated_at,
            "lsd_version": lsd_version,
            "compiler_model": compiler_model,
            "output_mode": "full_package",
        },
        "source_dependency": {
            "canonical_url": fetch.canonical_url,
            "source_title": fetch.title,
            "active_source_version": "source_v1",
            "local_source_file": "source.md",
            "last_checked_at": generated_at,
            "last_successful_fetch_at": generated_at,
            "normalized_hash": norm_hash,
            "archive_urls": [],
            "update_mode": "monitored",
            "promotion_policy": "manual_approval",
            "fallback_order": [
                "local_copy", "wayback_snapshot",
                "secondary_archive", "previous_version",
            ],
        },
        "ingestion": {
            "mode": mode,
            "text_extraction_confidence": _text_confidence(fit),
            "visual_extraction_enabled": mode in ("hybrid", "visual-first"),
            "reconciliation_required": mode in ("hybrid", "visual-first"),
            "visual_artifacts": visual_artifacts,
            "routing_notes": ctx.ingestion.routing_notes,
        },
        "source_fit": {
            "overall_fit": fit.overall_fit,
            "rule_density": fit.rule_density,
            "procedure_density": fit.procedure_density,
            "example_density": fit.example_density,
            "stability": fit.stability,
            "specificity": fit.specificity,
            "composability": fit.composability,
            "fit_notes": fit.fit_notes,
        },
        "opportunity_summary": {
            "recommended_action": opp.recommended_action,
            "recommended_skill_type": opp.recommended_skill_type,
            "candidate_skill_types": [
                {
                    "type": c.type,
                    "confidence": c.confidence,
                    "build_timing": c.build_timing,
                    "why_fit": c.why_fit,
                    "needed_extras": c.needed_extras,
                }
                for c in opp.candidates
            ],
        },
        "governance": {
            "criticality": "medium",
            "review_required_for_promotion": True,
            "auto_update_threshold": "never",
            "change_classification_policy": "unchanged/minor/substantial/gone/redirected",
            "policy_notes": "Review all source changes before promoting an updated skill.",
        },
        "artifacts": {
            "readme_file": "README.md",
            "skill_file": "SKILL.md",
            "source_file": "source.md",
            "source_policy_file": "source-policy.md",
            "opportunity_map_file": "skill-opportunities.md",
            "extraction_report_file": "extraction-report.md",
            "changelog_file": "CHANGELOG.md",
            "visual_files": visual_artifacts,
        },
    }


def _build_metadata_multi(
    ctx: MultiSourceBuildContext,
    generated_at: str,
    compiler_model: str | None,
) -> dict:
    """Build metadata.json for a multi-source package. compiler_model is now populated."""
    opp = ctx.combined_opportunities
    return {
        "package": {
            "version": "0.3.0",
            "generated_at": generated_at,
            "lsd_version": lsd_version,
            "output_mode": "multi_source",
            "compiler_model": compiler_model,   # populated by compile_skill_multi()
        },
        "source_dependencies": [
            {
                "index": e.index,
                "url": e.url,
                "source_type": e.source_type if isinstance(e.source_type, str) else str(e.source_type),
                "ingestion_mode": e.ingestion_mode if isinstance(e.ingestion_mode, str) else str(e.ingestion_mode),
                "normalized_hash": content_hash(e.normalised),
                "last_checked_at": generated_at,
                "overall_fit": getattr(e.fit, "overall_fit", "unknown"),
                "fallback_order": [
                    "local_copy", "wayback_snapshot",
                    "secondary_archive", "previous_version",
                ],
            }
            for e in ctx.sources
        ],
        "conflict_summary": ctx.conflict_report.summary,
        "has_blocking_conflicts": ctx.conflict_report.has_blocking_conflicts,
        "opportunity_summary": {
            "recommended_action": opp.recommended_action,
            "recommended_skill_type": opp.recommended_skill_type,
            "candidate_count": len(opp.candidates),
        },
        "governance": {
            "review_required_for_promotion": True,
            "auto_update_threshold": "never",
            "change_classification_policy": "unchanged/minor/substantial/gone/redirected",
        },
        "artifacts": {
            "readme_file": "README.md",
            "skill_file": "SKILL.md",
            "index_file": "index.md",
            "sources_index_file": "sources-index.md",
            "conflicts_file": "conflicts.md",
            "opportunity_map_file": "skill-opportunities.md",
            "metadata_file": "metadata.json",
        },
    }


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _text_confidence(fit) -> str:
    if fit.rule_density == "high" and fit.example_density == "high":
        return "high"
    if fit.rule_density == "low" and fit.procedure_density == "low":
        return "low"
    return "medium"


def _source_policy(url: str, mode: str) -> str:
    visual_line = "- Visual artifacts: none" if mode == "text-first" else \
        "- Visual artifacts: visual/rendered-page.png, visual/tiles/"
    reconcile_line = "- Reconciliation required: yes" if mode != "text-first" else ""

    return f"""# Source Policy

## Canonical source
- URL: {url}
- Active source version: source_v1
- Local artifact: source.md

## Ingestion mode
- Mode: {mode}
{visual_line}
{reconcile_line}

## Update mode
- Mode: monitored
- Promotion policy: manual approval

## Refresh workflow
1. Run `lsd check <package-dir>` to compare normalized hash.
2. Classify change: unchanged / minor / substantial / gone / redirected.
3. Unchanged: no action. Minor: prepare update candidate. Substantial: new
   source version + skill draft, require explicit user decision.
4. Gone: do not overwrite. Use fallback chain below.
5. Never promote without review.

## Fallback order
1. Local source artifact (source.md)
2. Wayback Machine snapshot
3. Secondary archive
4. Previous approved version
"""


def _opportunities_md(opp) -> str:
    lines = ["# Skill Opportunity Map", ""]
    lines.append(f"## Recommended action: {opp.recommended_action}")
    lines.append(f"## Recommended skill type: {opp.recommended_skill_type}")
    lines.append("")
    lines.append("## Candidates")
    lines.append("")
    for c in opp.candidates:
        lines.append(f"### {c.type}")
        lines.append(f"- Confidence: {c.confidence}")
        lines.append(f"- Build timing: {c.build_timing}")
        lines.append(f"- Why: {c.why_fit}")
        if c.needed_extras:
            lines.append(f"- Needed extras: {', '.join(c.needed_extras)}")
        lines.append("")
    return "\n".join(lines)


def _extraction_report(ctx: BuildContext) -> str:
    fetch = ctx.ingestion.fetch
    fit = ctx.source_fit
    opp = ctx.opportunity_map
    mode = ctx.ingestion.mode

    return f"""# Extraction Report

## Decision

Build action: {opp.recommended_action}
Primary skill type: {opp.recommended_skill_type}
Ingestion mode: {mode}

## Source profile

- URL: {fetch.canonical_url}
- Title: {fetch.title}
- Word count: {fetch.word_count}
- Overall fit: {fit.overall_fit}

## Fit scores

- Rule density: {fit.rule_density}
- Procedure density: {fit.procedure_density}
- Example density: {fit.example_density}
- Stability: {fit.stability}
- Specificity: {fit.specificity}
- Composability: {fit.composability}

## Notes

{fit.fit_notes}

## Routing rationale

{ctx.ingestion.routing_notes}

## Maintenance note

Review source changes before promoting any skill update.
Run `lsd check <package-dir>` to detect drift.
"""
