"""Write a complete LSD skill package to disk."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from lsd import __version__ as lsd_version
from lsd.compiler import compile_skill, compile_skill_multi
from lsd.models import BuildContext, MultiSourceBuildContext
from lsd.normaliser import content_hash, normalise


def write_package(ctx: BuildContext) -> Path:
    """Write all package files to ctx.output_dir. Returns the output directory."""
    out = ctx.output_dir
    out.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).isoformat()
    ctx.generated_at = generated_at

    fetch = ctx.ingestion.fetch
    mode = ctx.ingestion.mode
    opp = ctx.opportunity_map

    normalised = normalise(fetch)
    norm_hash = content_hash(normalised)

    # Compile SKILL.md and capture the model that did it
    skill_content, compiler_model = compile_skill(ctx)
    (out / "SKILL.md").write_text(skill_content)

    # source.md
    (out / "source.md").write_text(normalised)

    # metadata.json — includes compiler_model
    (out / "metadata.json").write_text(
        json.dumps(_build_metadata(ctx, norm_hash, generated_at, compiler_model), indent=2)
    )

    # source-policy.md
    (out / "source-policy.md").write_text(_source_policy(fetch.canonical_url, mode))

    # skill-opportunities.md
    (out / "skill-opportunities.md").write_text(_opportunities_md(opp))

    # extraction-report.md — now includes Limitations + token stats
    (out / "extraction-report.md").write_text(_extraction_report(ctx))

    # CHANGELOG.md
    (out / "CHANGELOG.md").write_text(
        f"# Changelog\n\n## 0.1.0 — {generated_at[:10]}\n- Initial package generated by LSD.\n"
    )

    # README.md — first-class package output (agent entry point for versioning)
    (out / "README.md").write_text(
        _readme(ctx, norm_hash, generated_at, compiler_model)
    )

    # visual/ placeholder for hybrid/visual-first
    if mode in ("hybrid", "visual-first"):
        visual_dir = out / "visual" / "tiles"
        visual_dir.mkdir(parents=True, exist_ok=True)
        (out / "visual" / ".gitkeep").touch()

    # scripts/ — emit maintenance helpers
    scripts_dir = out / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    (scripts_dir / "check-drift.py").write_text(_check_drift_script(out))
    (scripts_dir / "motivation-check.py").write_text(_motivation_check_script())

    return out


def write_multi_package(ctx: MultiSourceBuildContext) -> Path:
    """Write multi-source build artifacts to ctx.output_dir.

    Compiles SKILL.md (with compiler_model) inside this function so the
    model id is available for metadata.json and README.md. Retrieval
    backend is taken from ctx._retrieval_backend / ctx._retrieval_index
    if available (set by pipeline.build_multi).
    """
    out = ctx.output_dir
    out.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).isoformat()

    # Per-source files
    for entry in ctx.sources:
        path = out / f"source-{entry.index}.md"
        path.write_text(entry.normalised, encoding="utf-8")

    # sources-index.md
    lines: list[str] = [
        "# Sources Index\n\n",
        f"Built: {generated_at}\n\n",
        f"Sources: {len(ctx.sources)}\n\n",
        "| # | URL | Type | Mode | Overall Fit |\n",
        "|---|-----|------|------|-------------|\n",
    ]
    for e in ctx.sources:
        source_type = e.source_type if isinstance(e.source_type, str) else str(e.source_type)
        ingestion_mode = e.ingestion_mode if isinstance(e.ingestion_mode, str) else str(e.ingestion_mode)
        overall_fit = getattr(e.fit, "overall_fit", "—")
        lines.append(
            f"| {e.index} | {e.url} | {source_type} | {ingestion_mode} | {overall_fit} |\n"
        )
    (out / "sources-index.md").write_text("".join(lines), encoding="utf-8")

    # conflicts.md
    conflict_lines: list[str] = [
        "# Conflict Report\n\n",
        f"{ctx.conflict_report.summary}\n\n",
    ]
    if ctx.conflict_report.has_blocking_conflicts:
        conflict_lines.append(
            "> **Warning:** High-severity contradictions detected. "
            "Review before using this skill.\n\n"
        )
    if not ctx.conflict_report.conflicts:
        conflict_lines.append("No conflicts detected.\n")
    else:
        for i, c in enumerate(ctx.conflict_report.conflicts, 1):
            conflict_lines.extend([
                f"## Conflict {i}: {c.kind.title()} [{c.severity.upper()}]\n\n",
                f"**Sources involved:** {', '.join(str(s) for s in c.source_indices)}\n\n",
                f"**Description:** {c.description}\n\n",
                f"**Suggestion:** {c.suggestion}\n\n",
            ])
    (out / "conflicts.md").write_text("".join(conflict_lines), encoding="utf-8")

    # skill-opportunities.md
    opp = ctx.combined_opportunities
    (out / "skill-opportunities.md").write_text(_opportunities_md(opp), encoding="utf-8")

    # Compile SKILL.md — retrieval backend may be pre-attached by build_multi()
    ret_backend = getattr(ctx, "_retrieval_backend", None)
    ret_index = getattr(ctx, "_retrieval_index", None)
    skill_content, compiler_model = compile_skill_multi(
        ctx,
        retrieval_backend=ret_backend if ret_index is not None else None,
    )
    (out / "SKILL.md").write_text(skill_content, encoding="utf-8")

    # metadata.json — v0.5 schema, compiler_model now populated
    meta = _build_metadata_multi(ctx, generated_at, compiler_model)
    (out / "metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    # README.md — agent entry point for versioning (multi-source variant)
    (out / "README.md").write_text(
        _readme_multi(ctx, generated_at, compiler_model), encoding="utf-8"
    )

    # index.md
    index_lines: list[str] = [
        "# LSD Multi-Source Build\n\n",
        f"Sources: {len(ctx.sources)}\n\n",
        "## Files\n\n",
    ]
    for e in ctx.sources:
        index_lines.append(f"- [source-{e.index}.md](source-{e.index}.md) — {e.url}\n")
    index_lines.extend([
        "- [sources-index.md](sources-index.md)\n",
        "- [conflicts.md](conflicts.md)\n",
        "- [skill-opportunities.md](skill-opportunities.md)\n",
        "- [metadata.json](metadata.json)\n",
        "- [README.md](README.md)\n",
        "- [SKILL.md](SKILL.md)\n",
    ])
    (out / "index.md").write_text("".join(index_lines), encoding="utf-8")

    # scripts/ — emit maintenance helpers
    scripts_dir = out / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    (scripts_dir / "check-drift.py").write_text(_check_drift_script(out))
    (scripts_dir / "motivation-check.py").write_text(_motivation_check_script())

    return out


# ---------------------------------------------------------------------------
# README generators
# ---------------------------------------------------------------------------

def _readme(ctx: BuildContext, norm_hash: str, generated_at: str, compiler_model: str | None) -> str:
    """Generate README.md — the agent's entry point for this skill package."""
    fetch = ctx.ingestion.fetch
    fit = ctx.source_fit
    opp = ctx.opportunity_map
    mode = ctx.ingestion.mode

    skill_type = opp.recommended_skill_type.replace("_", " ").title()
    compiler_note = (
        f"Compiled by `{compiler_model}`."
        if compiler_model
        else "Compiled with heuristic fallback (no LLM configured)."
    )

    candidate_rows = "\n".join(
        f"| {c.type} | {c.confidence} | {c.build_timing} | {c.why_fit} |"
        for c in opp.candidates
    )

    # Tool candidates (if any)
    tool_section = ""
    if opp.tool_candidates:
        tc_rows = "\n".join(
            f"| {tc.type} | {tc.confidence} | {tc.why_fit} |"
            for tc in opp.tool_candidates
        )
        tool_section = f"""
## Tool candidates

This source may be better served as a tool rather than a skill:

| Type | Confidence | Rationale |
|------|-----------|-----------|
{tc_rows}

See `skill-opportunities.md` for details.
"""

    # Limitations block (if any)
    limitations_section = ""
    if opp.assessment and opp.assessment.limitations:
        lims = "\n".join(f"- {lim}" for lim in opp.assessment.limitations)
        limitations_section = f"""
## Known limitations

{lims}
"""
        if opp.assessment.recommended_rebuild_cadence:
            limitations_section += f"\nRecommended rebuild cadence: **{opp.assessment.recommended_rebuild_cadence}**\n"

    return f"""# {skill_type} — LSD Skill Package

> Auto-generated by [LSD](https://github.com/moondocksaint/lsd) v{lsd_version}.
> Review and refine before promoting to production use.

## When to use

Use this skill for **{skill_type.lower()}** tasks drawing on:
- Source: [{fetch.title}]({fetch.canonical_url})
{tool_section}{limitations_section}
## Package structure

```
<package-dir>/
├── README.md               ← you are here; start here for versioning
├── SKILL.md                ← load this into your agent
├── source.md               ← normalised source text
├── source-policy.md        ← update policy, fallback chain
├── skill-opportunities.md  ← other skill types this source supports
├── extraction-report.md    ← classification scores and routing rationale
├── metadata.json           ← machine-readable provenance (hash, model, timestamps)
├── CHANGELOG.md            ← human-readable version history
└── scripts/
    ├── check-drift.py      ← detect source drift (run manually or in CI)
    └── motivation-check.py ← verify original build motivation still applies
```

## Version & update workflow

Run `lsd check <package-dir>` to detect source drift. Change states:
- **Unchanged** — hash identical, no action needed
- **Minor** — content changed, structure intact; offer rebuild
- **Substantial** — major rewrite; warn user, do not auto-overwrite
- **Gone** — 404/unreachable; preserve existing package, use fallback chain
- **Redirected** — URL moved; offer to update canonical URL

Machine-readable provenance in `metadata.json`:
- `source_dependency.normalized_hash` — fingerprint of the normalised source
- `source_dependency.last_checked_at` — timestamp of last fetch
- `package.compiler_model` — which LLM compiled the skill sections
- `package.lsd_version` — LSD version that built this package

## Source provenance

| Field | Value |
|-------|-------|
| URL | [{fetch.canonical_url}]({fetch.canonical_url}) |
| Title | {fetch.title} |
| Ingestion mode | `{mode}` |
| Overall fit | `{fit.overall_fit}` |
| Rule density | `{fit.rule_density}` |
| Example density | `{fit.example_density}` |
| Content hash | `{norm_hash}` |
| Built at | `{generated_at}` |
| Compiler | `{compiler_model or "heuristic (no LLM)"}` |
| LSD version | `{lsd_version}` |

## Skill opportunities

| Type | Confidence | Timing | Rationale |
|------|-----------|--------|-----------|
{candidate_rows}

## Governance

- Promotion policy: **manual approval required**
- Auto-update threshold: **never**
- Change classification: unchanged / minor / substantial / gone / redirected
- Review `source-policy.md` before promoting any update.

---

*{compiler_note} Generated by LSD v{lsd_version}.*
"""


def _readme_multi(
    ctx: MultiSourceBuildContext,
    generated_at: str,
    compiler_model: str | None,
) -> str:
    """Generate README.md for a multi-source skill package."""
    opp = ctx.combined_opportunities
    skill_type = opp.recommended_skill_type.replace("_", " ").title()
    compiler_note = (
        f"Compiled by `{compiler_model}`."
        if compiler_model
        else "Compiled with heuristic fallback (no LLM configured)."
    )

    source_rows = "\n".join(
        f"| {e.index} | [{e.url}]({e.url}) | "
        f"`{content_hash(e.normalised)}` | "
        f"`{getattr(e.fit, 'overall_fit', '—')}` |"
        for e in ctx.sources
    )

    conflict_note = ""
    if ctx.conflict_report.has_blocking_conflicts:
        conflict_note = (
            "\n> **Warning:** Blocking conflicts detected across sources. "
            "See `conflicts.md` before using this skill.\n"
        )
    elif ctx.conflict_report.conflicts:
        conflict_note = f"\n> Note: {ctx.conflict_report.summary} See `conflicts.md`.\n"

    # Token / truncation note
    token_note = ""
    estimated_tokens = getattr(ctx, "estimated_tokens", 0)
    ret_index = getattr(ctx, "_retrieval_index", None)
    was_truncated = getattr(ret_index, "was_truncated", False) if ret_index else False
    if was_truncated:
        token_note = (
            f"\n> **Note:** Combined source text (~{estimated_tokens:,} tokens) exceeded "
            "the token threshold. The retrieval backend truncated content before compilation. "
            "Some source material may be absent from `SKILL.md`.\n"
        )
    elif estimated_tokens:
        token_note = f"\n> Combined source text: ~{estimated_tokens:,} estimated tokens.\n"

    # Tool candidates
    tool_section = ""
    if opp.tool_candidates:
        tc_rows = "\n".join(
            f"| {tc.type} | {tc.confidence} | {tc.why_fit} |"
            for tc in opp.tool_candidates
        )
        tool_section = f"""
## Tool candidates

One or more sources may be better served as tools rather than skills:

| Type | Confidence | Rationale |
|------|-----------|-----------|
{tc_rows}
"""

    # Limitations
    limitations_section = ""
    if opp.assessment and opp.assessment.limitations:
        lims = "\n".join(f"- {lim}" for lim in opp.assessment.limitations)
        limitations_section = f"\n## Known limitations\n\n{lims}\n"

    return f"""# {skill_type} (Multi-Source) — LSD Skill Package

> Auto-generated by [LSD](https://github.com/moondocksaint/lsd) v{lsd_version}
> from {len(ctx.sources)} sources.
> Review and refine before promoting to production use.
{conflict_note}{token_note}
## When to use

Use this skill for **{skill_type.lower()}** tasks that draw on multiple sources.
Each claim in `SKILL.md` is cited with [Source N] for traceability.
{tool_section}{limitations_section}
## Package structure

```
<package-dir>/
├── README.md               ← you are here; start here for versioning
├── SKILL.md                ← load this into your agent (multi-source compiled)
├── index.md                ← package overview and file map
├── sources-index.md        ← fetch status and fit scores per source
├── source-1.md … source-N.md  ← normalised per-source text
├── conflicts.md            ← cross-source gaps, contradictions, overlaps
├── skill-opportunities.md  ← skill types detected across all sources
├── metadata.json           ← machine-readable provenance
└── scripts/
    ├── check-drift.py      ← detect source drift (run manually or in CI)
    └── motivation-check.py ← verify original build motivation still applies
```

## Version & update workflow

Run `lsd check <package-dir>` to detect drift in any source. Drift in
any one source triggers a check report for all sources. Change states:
- **Unchanged** — all hashes identical, no action needed
- **Minor** — one or more sources changed, structure intact
- **Substantial** — major rewrite in any source; warn, do not auto-overwrite
- **Gone** — a source URL is 404/unreachable; preserve package, use fallback
- **Redirected** — a source URL moved; offer to update canonical URL

## Source provenance

| # | URL | Content Hash | Overall Fit |
|---|-----|-------------|-------------|
{source_rows}

| Field | Value |
|-------|-------|
| Built at | `{generated_at}` |
| Compiler | `{compiler_model or "heuristic (no LLM)"}` |
| LSD version | `{lsd_version}` |
| Conflicts | {ctx.conflict_report.summary} |

## Governance

- Promotion policy: **manual approval required**
- Auto-update threshold: **never**
- Resolve all blocking conflicts in `conflicts.md` before promoting.

---

*{compiler_note} Generated by LSD v{lsd_version}.*
"""


# ---------------------------------------------------------------------------
# Metadata builders
# ---------------------------------------------------------------------------

def _build_metadata(
    ctx: BuildContext,
    norm_hash: str,
    generated_at: str,
    compiler_model: str | None = None,
) -> dict:
    fetch = ctx.ingestion.fetch
    mode = ctx.ingestion.mode
    fit = ctx.source_fit
    opp = ctx.opportunity_map

    visual_artifacts: list[str] = []
    if mode in ("hybrid", "visual-first"):
        visual_artifacts = ["visual/rendered-page.png", "visual/tiles/"]

    # Assessment block — included when populated
    assessment_block: dict = {}
    if opp.assessment:
        assessment_block = {
            "verdict": opp.assessment.skill_fit_verdict,
            "limitations": opp.assessment.limitations,
            "better_alternatives": opp.assessment.better_alternatives,
            "tool_candidate_count": len(opp.tool_candidates),
            "stability_warning": opp.assessment.stability_warning,
            "breadth_warning": opp.assessment.breadth_warning,
            "recommended_rebuild_cadence": opp.assessment.recommended_rebuild_cadence,
        }

    return {
        "package": {
            "name": opp.recommended_skill_type.replace("_", " ").title(),
            "version": "0.1.0",
            "generated_at": generated_at,
            "lsd_version": lsd_version,
            "compiler_model": compiler_model,
            "output_mode": "full_package",
        },
        "source_dependency": {
            "canonical_url": fetch.canonical_url,
            "source_title": fetch.title,
            "active_source_version": "source_v1",
            "local_source_file": "source.md",
            "last_checked_at": generated_at,
            "last_successful_fetch_at": generated_at,
            "normalized_hash": norm_hash,
            "archive_urls": [],
            "update_mode": "monitored",
            "promotion_policy": "manual_approval",
            "fallback_order": [
                "local_copy", "wayback_snapshot",
                "secondary_archive", "previous_version",
            ],
        },
        "ingestion": {
            "mode": mode,
            "text_extraction_confidence": _text_confidence(fit),
            "visual_extraction_enabled": mode in ("hybrid", "visual-first"),
            "reconciliation_required": mode in ("hybrid", "visual-first"),
            "visual_artifacts": visual_artifacts,
            "routing_notes": ctx.ingestion.routing_notes,
        },
        "source_fit": {
            "overall_fit": fit.overall_fit,
            "rule_density": fit.rule_density,
            "procedure_density": fit.procedure_density,
            "example_density": fit.example_density,
            "stability": fit.stability,
            "specificity": fit.specificity,
            "composability": fit.composability,
            "fit_notes": fit.fit_notes,
        },
        "opportunity_summary": {
            "recommended_action": opp.recommended_action,
            "recommended_skill_type": opp.recommended_skill_type,
            "candidate_skill_types": [
                {
                    "type": c.type,
                    "confidence": c.confidence,
                    "build_timing": c.build_timing,
                    "why_fit": c.why_fit,
                    "needed_extras": c.needed_extras,
                }
                for c in opp.candidates
            ],
            "tool_candidates": [
                {
                    "type": tc.type,
                    "confidence": tc.confidence,
                    "why_fit": tc.why_fit,
                    "build_timing": tc.build_timing,
                }
                for tc in opp.tool_candidates
            ],
            "assessment": assessment_block,
        },
        "governance": {
            "criticality": "medium",
            "review_required_for_promotion": True,
            "auto_update_threshold": "never",
            "change_classification_policy": "unchanged/minor/substantial/gone/redirected",
            "policy_notes": "Review all source changes before promoting an updated skill.",
        },
        "artifacts": {
            "readme_file": "README.md",
            "skill_file": "SKILL.md",
            "source_file": "source.md",
            "source_policy_file": "source-policy.md",
            "opportunity_map_file": "skill-opportunities.md",
            "extraction_report_file": "extraction-report.md",
            "changelog_file": "CHANGELOG.md",
            "scripts": ["scripts/check-drift.py", "scripts/motivation-check.py"],
            "visual_files": visual_artifacts,
        },
    }


def _build_metadata_multi(
    ctx: MultiSourceBuildContext,
    generated_at: str,
    compiler_model: str | None,
) -> dict:
    """Build metadata.json for a multi-source package. compiler_model is now populated."""
    opp = ctx.combined_opportunities
    estimated_tokens = getattr(ctx, "estimated_tokens", 0)
    ret_index = getattr(ctx, "_retrieval_index", None)
    was_truncated = getattr(ret_index, "was_truncated", False) if ret_index else False

    assessment_block: dict = {}
    if opp.assessment:
        assessment_block = {
            "verdict": opp.assessment.skill_fit_verdict,
            "limitations": opp.assessment.limitations,
            "better_alternatives": opp.assessment.better_alternatives,
            "tool_candidate_count": len(opp.tool_candidates),
            "stability_warning": opp.assessment.stability_warning,
            "breadth_warning": opp.assessment.breadth_warning,
            "recommended_rebuild_cadence": opp.assessment.recommended_rebuild_cadence,
        }

    return {
        "package": {
            "version": "0.3.0",
            "generated_at": generated_at,
            "lsd_version": lsd_version,
            "output_mode": "multi_source",
            "compiler_model": compiler_model,   # populated by compile_skill_multi()
        },
        "source_dependencies": [
            {
                "index": e.index,
                "url": e.url,
                "source_type": e.source_type if isinstance(e.source_type, str) else str(e.source_type),
                "ingestion_mode": e.ingestion_mode if isinstance(e.ingestion_mode, str) else str(e.ingestion_mode),
                "normalized_hash": content_hash(e.normalised),
                "last_checked_at": generated_at,
                "overall_fit": getattr(e.fit, "overall_fit", "unknown"),
                "fallback_order": [
                    "local_copy", "wayback_snapshot",
                    "secondary_archive", "previous_version",
                ],
            }
            for e in ctx.sources
        ],
        "conflict_summary": ctx.conflict_report.summary,
        "has_blocking_conflicts": ctx.conflict_report.has_blocking_conflicts,
        "retrieval": {
            "estimated_tokens": estimated_tokens,
            "was_truncated": was_truncated,
            "backend": getattr(ret_index, "backend_name", None) if ret_index else None,
        },
        "opportunity_summary": {
            "recommended_action": opp.recommended_action,
            "recommended_skill_type": opp.recommended_skill_type,
            "candidate_count": len(opp.candidates),
            "tool_candidate_count": len(opp.tool_candidates),
            "assessment": assessment_block,
        },
        "governance": {
            "review_required_for_promotion": True,
            "auto_update_threshold": "never",
            "change_classification_policy": "unchanged/minor/substantial/gone/redirected",
        },
        "artifacts": {
            "readme_file": "README.md",
            "skill_file": "SKILL.md",
            "index_file": "index.md",
            "sources_index_file": "sources-index.md",
            "conflicts_file": "conflicts.md",
            "opportunity_map_file": "skill-opportunities.md",
            "metadata_file": "metadata.json",
            "scripts": ["scripts/check-drift.py", "scripts/motivation-check.py"],
        },
    }


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _text_confidence(fit) -> str:
    if fit.rule_density == "high" and fit.example_density == "high":
        return "high"
    if fit.rule_density == "low" and fit.procedure_density == "low":
        return "low"
    return "medium"


def _source_policy(url: str, mode: str) -> str:
    visual_line = "- Visual artifacts: none" if mode == "text-first" else \
        "- Visual artifacts: visual/rendered-page.png, visual/tiles/"
    reconcile_line = "- Reconciliation required: yes" if mode != "text-first" else ""

    return f"""# Source Policy

## Canonical source
- URL: {url}
- Active source version: source_v1
- Local artifact: source.md

## Ingestion mode
- Mode: {mode}
{visual_line}
{reconcile_line}

## Update mode
- Mode: monitored
- Promotion policy: manual approval

## Refresh workflow
1. Run `lsd check <package-dir>` to compare normalized hash.
2. Classify change: unchanged / minor / substantial / gone / redirected.
3. Unchanged: no action. Minor: prepare update candidate. Substantial: new
   source version + skill draft, require explicit user decision.
4. Gone: do not overwrite. Use fallback chain below.
5. Never promote without review.

## Fallback order
1. Local source artifact (source.md)
2. Wayback Machine snapshot
3. Secondary archive
4. Previous approved version
"""


def _opportunities_md(opp) -> str:
    lines = ["# Skill Opportunity Map", ""]
    lines.append(f"## Recommended action: {opp.recommended_action}")
    lines.append(f"## Recommended skill type: {opp.recommended_skill_type}")
    lines.append("")

    # Honest assessment
    if opp.assessment:
        a = opp.assessment
        lines.append("## Assessment")
        lines.append("")
        lines.append(f"**Verdict:** {a.skill_fit_verdict}")
        if a.limitations:
            lines.append("")
            lines.append("**Limitations:**")
            for lim in a.limitations:
                lines.append(f"- {lim}")
        if a.better_alternatives:
            lines.append("")
            lines.append("**Better alternatives considered:**")
            for alt in a.better_alternatives:
                lines.append(f"- {alt}")
        if a.stability_warning:
            lines.append("")
            lines.append(f"> **Stability warning:** {a.stability_warning}")
        if a.breadth_warning:
            lines.append("")
            lines.append(f"> **Breadth warning:** {a.breadth_warning}")
        if a.recommended_rebuild_cadence:
            lines.append("")
            lines.append(f"**Recommended rebuild cadence:** {a.recommended_rebuild_cadence}")
        lines.append("")

    lines.append("## Skill candidates")
    lines.append("")
    for c in opp.candidates:
        lines.append(f"### {c.type}")
        lines.append(f"- Confidence: {c.confidence}")
        lines.append(f"- Build timing: {c.build_timing}")
        lines.append(f"- Why: {c.why_fit}")
        if c.needed_extras:
            lines.append(f"- Needed extras: {', '.join(c.needed_extras)}")
        lines.append("")

    if opp.tool_candidates:
        lines.append("## Tool candidates")
        lines.append("")
        lines.append(
            "The following tool types may serve this source better than a skill.\n"
            "Consider building a tool instead of (or alongside) a skill.\n"
        )
        for tc in opp.tool_candidates:
            lines.append(f"### {tc.type}")
            lines.append(f"- Confidence: {tc.confidence}")
            lines.append(f"- Build timing: {tc.build_timing}")
            lines.append(f"- Why: {tc.why_fit}")
            if tc.needed_extras:
                lines.append(f"- Needed extras: {', '.join(tc.needed_extras)}")
            lines.append("")

    return "\n".join(lines)


def _extraction_report(ctx: BuildContext) -> str:
    fetch = ctx.ingestion.fetch
    fit = ctx.source_fit
    opp = ctx.opportunity_map
    mode = ctx.ingestion.mode

    # Limitations block
    limitations_block = ""
    if opp.assessment and opp.assessment.limitations:
        lim_lines = "\n".join(f"- {lim}" for lim in opp.assessment.limitations)
        limitations_block = f"""
## Limitations

{lim_lines}
"""
        if opp.assessment.stability_warning:
            limitations_block += f"\n**Stability:** {opp.assessment.stability_warning}\n"
        if opp.assessment.breadth_warning:
            limitations_block += f"\n**Breadth:** {opp.assessment.breadth_warning}\n"
        if opp.assessment.better_alternatives:
            alts = "\n".join(f"- {a}" for a in opp.assessment.better_alternatives)
            limitations_block += f"\n**Better alternatives considered:**\n{alts}\n"

    # Tool candidates note
    tool_note = ""
    if opp.tool_candidates:
        tc_list = ", ".join(tc.type for tc in opp.tool_candidates)
        tool_note = f"\n## Tool opportunity\n\nThis source triggered tool candidate detection: {tc_list}.\nSee skill-opportunities.md for details.\n"

    return f"""# Extraction Report

## Decision

Build action: {opp.recommended_action}
Primary skill type: {opp.recommended_skill_type}
Ingestion mode: {mode}

## Source profile

- URL: {fetch.canonical_url}
- Title: {fetch.title}
- Word count: {fetch.word_count}
- Overall fit: {fit.overall_fit}

## Fit scores

- Rule density: {fit.rule_density}
- Procedure density: {fit.procedure_density}
- Example density: {fit.example_density}
- Stability: {fit.stability}
- Specificity: {fit.specificity}
- Composability: {fit.composability}

## Notes

{fit.fit_notes}

## Routing rationale

{ctx.ingestion.routing_notes}
{limitations_block}{tool_note}
## Maintenance note

Review source changes before promoting any skill update.
Run `lsd check <package-dir>` to detect drift.
"""


# ---------------------------------------------------------------------------
# Script generators
# ---------------------------------------------------------------------------

def _check_drift_script(package_dir: Path) -> str:
    """Generate scripts/check-drift.py — a standalone drift-check helper."""
    return f'''#!/usr/bin/env python3
"""check-drift.py — Detect source drift for this skill package.

Auto-generated by LSD. Run from the project root or from this package
directory to check whether the upstream source has changed since the
last build.

Usage:
    python scripts/check-drift.py
    python scripts/check-drift.py --url <override-url>

Requires: lsd to be installed (pip install lsd).
Exit codes: 0 = UNCHANGED, 1 = drift detected, 2 = error.
"""
import argparse
import subprocess
import sys
from pathlib import Path

PACKAGE_DIR = Path(__file__).parent.parent  # one level up from scripts/


def main() -> int:
    parser = argparse.ArgumentParser(description="Check upstream source drift.")
    parser.add_argument("--url", default=None, help="Override canonical URL.")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    cmd = ["lsd", "check", str(PACKAGE_DIR)]
    if args.url:
        cmd += ["--url", args.url]

    result = subprocess.run(cmd, capture_output=not args.verbose)

    if result.returncode == 0 and not args.verbose:
        print("UNCHANGED — no drift detected.")

    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
'''


def _motivation_check_script() -> str:
    """Generate scripts/motivation-check.py — validate build motivation still holds."""
    return '''#!/usr/bin/env python3
"""motivation-check.py — Verify that the original build motivation still applies.

Auto-generated by LSD. Run after a drift event to decide whether the
updated source still warrants a skill — or whether the motivation has
been superseded (source gone, topic made obsolete, better alternative now
available, etc.).

Usage:
    python scripts/motivation-check.py
    python scripts/motivation-check.py --motivation-file path/to/motivation.json

Reads motivation.json from the package directory (if present). If the
file is absent, prints a checklist to evaluate manually.

Exit codes: 0 = motivation still valid (manual confirmation), 1 = check needed.
"""
import json
import sys
from pathlib import Path

PACKAGE_DIR = Path(__file__).parent.parent  # one level up from scripts/
DEFAULT_MOTIVATION_FILE = PACKAGE_DIR / "motivation.json"

CHECKLIST = [
    "Is the original intent still relevant to the audience?",
    "Does the updated source still cover the key concepts?",
    "Has a better alternative (tool, API, newer source) emerged?",
    "Are the known limitations still acceptable for the use case?",
    "Has the recommended rebuild cadence elapsed without a rebuild?",
]


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="Check build motivation validity.")
    parser.add_argument(
        "--motivation-file",
        default=str(DEFAULT_MOTIVATION_FILE),
        help="Path to motivation.json (default: <package>/motivation.json).",
    )
    args = parser.parse_args()

    mot_path = Path(args.motivation_file)
    if mot_path.exists():
        try:
            mot = json.loads(mot_path.read_text())
        except json.JSONDecodeError as exc:
            print(f"Could not parse motivation.json: {exc}", file=sys.stderr)
            return 2

        print("=== Motivation Check ===")
        print(f"Intent      : {mot.get('intent', '(not recorded)')}")
        print(f"Audience    : {mot.get('audience', '(not recorded)')}")
        print(f"Build mode  : {mot.get('build_mode', '(not recorded)')}")
        recorded_at = mot.get("recorded_at", "")
        if recorded_at:
            print(f"Recorded at : {recorded_at}")
        print()
        print("Key concepts:")
        for kc in mot.get("key_concepts", []):
            print(f"  - {kc}")
        print()
    else:
        print("motivation.json not found — using generic checklist.")
        print()

    print("=== Manual Checklist ===")
    print("Answer each question before deciding whether to rebuild:\\n")
    for i, item in enumerate(CHECKLIST, 1):
        print(f"  {i}. {item}")
    print()
    print("If any answer is NO or UNSURE, review the skill before promoting.")
    return 1  # always exit 1 to signal that human review is required


if __name__ == "__main__":
    sys.exit(main())
'''
